# Generated by Django 5.0.3 on 2024-03-05 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='post',
            name='created_datetime',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 5, 16, 35, 33, 645378, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=' ', max_length=50, unique=True),
        ),
    ]
